---

- name: Add Oracle Java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- raw: /bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- raw: /bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 seen true | sudo /usr/bin/debconf-set-selections

- name: Install Oracle JDK
  apt: pkg=oracle-java7-installer state=latest install_recommends=no update_cache=yes
