---
# This is the top-level playbook that defines our dev environment.

- hosts: all
  sudo: yes
  sudo_user: root
  user: tuhlmann
  gather_facts: no
  roles:
    - common
    - java-jdk
    - mongodb
    - chrome
    - gui-common
    - sbt
